config/routes.rb
ShoppingApp::Application.routes.draw do
  resources :selections

  devise_for :users
  resources :items
  resources :users, :only => [:show]

  get 'selections#show' => redirect('items#index')

  root 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base

  has_many :selections

end

app/models/selection.rb
class Selection < ActiveRecord::Base

  belongs_to :item
  belongs_to :user


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :selections
  has_many :items, through: :selections

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :config_permitted_parameters, if: :devise_controller?



  def config_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:email, :first_name, :last_name]
    devise_parameter_sanitizer.for(:sign_in) << :email
  end
end

app/controllers/concerns/users_controller.rb
def show
  @user = User.find(params[:id])
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end



  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :desc, :pic, :price)
    end
end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  before_action :set_selection, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /selections
  # GET /selections.json
  def index
    @user = current_user
    @selections = @user.selections
  end

  # GET /selections/1
  # GET /selections/1.json
  def show
  end

  # GET /selections/new
  def new
    @selection = Selection.new
  end

  # GET /selections/1/edit
  def edit
  end

  # POST /selections
  # POST /selections.json
  def create

respond_to do |format|
  format.json do
    @selection = Selection.new
    @selection.user_id = current_user.id
    @selection.item_id = params[:item_id]
    @selection.save
  end
end
end


  # PATCH/PUT /selections/1
  # PATCH/PUT /selections/1.json
  def update
    respond_to do |format|
      if @selection.update(selection_params)
        format.html { redirect_to @selection, notice: 'Selection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selections/1
  # DELETE /selections/1.json
  def destroy
    @selection.destroy
    respond_to do |format|
      format.html { redirect_to selections_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_selection
      @selection = Selection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def selection_params
      params.require(:selection).permit(:user_id, :item_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/selections_helper.rb
module SelectionsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :pic %><br>
    <%= f.text_field :pic %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class="store-container">
  <div class="cart">
    <h2>Drag here to add to Kart</h2>
  </div>
  <p class="notice">Item added to Kart</p>
  <div id="columns">
    <% @items.each do |item| %>
    <div class="item-holder" id="<%= item.id %>">
      <div class="pic"><%= link_to image_tag(item.pic), item %></div>
      <p class="name"><%= link_to item.name, item %></p>
      <p class="price"><i class="fa fa-money"></i> $<%= item.price %></p>
 	</div>
    <% end %>
</div>
</div>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<div class="container">
<div class="mycart">
	<p>Stuff You Want</p>
</div>

<p id="notice"><%= notice %></p>
<div class="detail">

	<%= image_tag(@item.pic) %>
	
	<div class="deets">
		<div class="det-name"><%= @item.name %>
		</div>

		<div class="det-price"><%= @item.price %>
		</div>

		<div class="det-desc"><%= @item.desc %>
		</div>

		<div class="cart">
			<%= link_to 'Add to Cart', new_selection_url(item_id: @item.id) %>
		</div>

		<div class = "det-links">
			<%= link_to 'Edit', edit_item_path(@item) %> |
			<%= link_to 'Back', items_path %>
		</div>
	</div>
</div>
</div>

app/views/layouts/_header.html.erb
<div class="nav-container">
  <div id="nav-columns">

  <div class="hm">
        <% if user_signed_in? %>
  <%= link_to 'Sign Out', destroy_user_session_path, method: 'delete', :class => "nav-item" %>
        <% else %>
  <%= link_to 'Sign In', new_user_session_path, :class => "nav-item" %>
        <% end %>


  </div>
    <div><%= link_to 'Browse the Store', items_url, :class => "nav-item" %>
    </div>

  <div><%= link_to 'Account Details', selections_url, :class => "nav-item" %></div>

   <div><%= link_to 'My Cart', selections_url, :class => "nav-item", :id => "mycart" %>
   </div>
</div>
      <!-- Left Nav Section -->
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Frijole' rel='stylesheet' type='text/css'>

    <title><%= content_for?(:title) ? yield(:title) : "Nerdz-R-Us" %></title>

  </head>

  <body>
    <ul class="rockets">
  <li><i class="fa fa-rocket" id="logo"></i></li>
  <li><i class="fa fa-rocket" id="logo"></i></li>
  <li><i class="fa fa-rocket" id="logo"></i></li>
  <li><i class="fa fa-rocket" id="logo"></i></li>
  <li><i class="fa fa-rocket" id="logo"></i></li>
  <li><i class="fa fa-rocket" id="logo"></i></li>
</ul>
  <h1 class="logo-name">Nerds 'R' Us</h1>

	<%= render "layouts/header" %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/store_front.html.erb
<div class="container">
	<ul class="whole-list">
		<li class="item">

		</li>
	</ul>
</div>

app/views/selections/_form.html.erb
<%= form_for(@selection) do |f| %>
  <% if @selection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@selection.errors.count, "error") %> prohibited this selection from being saved:</h2>

      <ul>
      <% @selection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :item_id, :value => params[:item_id] %>

  <div class="actions">
    <%= f.submit "Add"%>
  </div>
<% end %>

app/views/selections/edit.html.erb
<h1>Editing selection</h1>

<%= render 'form' %>

<%= link_to 'Show', @selection %> |
<%= link_to 'Back', selections_path %>

app/views/selections/index.html.erb
<h1><%= current_user.first_name %>'s Cart</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Quantity</th>
      <th>Cost</th>
    </tr>
  </thead>

  <tbody>
    <% item_ids = @selections.pluck(:item_id) %>
    <% items_ids = item_ids.uniq %>
    <% items_ids.each do |one_item| %>
      <% item = Item.find_by(id: one_item) %>
      <tr>
        <td><%= link_to item.name, item_url(item.id) %></td>
        <% id = item.id %>
        <% multiples = Selection.where(item_id: id) %>
        <td><%= multiples.count %></td>
        <td>$<%= item.price * multiples.count %></td>
      </tr>
    <% end %>
    <tr>
      <td>
      </td>
      <td>
        Total:
      </td>
      <td>
        <% items_ids.each do |one_item| %>
        <% item = Item.find_by(id: one_item) %>
        <% id = item.id %>
        <% multiples = Selection.where(item_id: id) %>
        <%= item.price * multiples.count %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

<br>

app/views/selections/new.html.erb
<h1>New selection</h1>

<%= render 'form' %>

<%= link_to 'Back', selections_path %>

app/views/selections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @selection.user_id %>
</p>

<p>
  <strong>Item:</strong>
  <%= @selection.item_id %>
</p>

<%= link_to 'Edit', edit_selection_path(@selection) %> |
<%= link_to 'Back', selections_path %>